# This is default and very simple configuration file for Yasb.
# For more information about configuration options, please visit the Wiki https://github.com/amnweb/yasb/wiki
watch_stylesheet: true
watch_config: true
debug: true
update_check: true # Enable automatic update check.
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ["primary"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 1000
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "System"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 6
      left: 6
      bottom: 0
      right: 6
    widgets:
      left: ["home","windows_workspaces","cava","cpu",
          "memory","todo"]
      center: ["clock"]
      right:
        ["media","traffic",
          "microphone",
          "volume",
          "notifications",
        ]
widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb81\udf17</span>"
      menu_list:
        - { title: "My Crib", path: "C:\\Users\\monst" }
        - { title: "Loot Bag", path: "C:\\Users\\monst\\Downloads" }
        - { title: "Boring Stuff", path: "C:\\Users\\monst\\Documents" }
        - { title: "Cursed Memories", path: "C:\\Users\\monst\\Pictures" }
      system_menu: true
      power_menu: true
      blur: false
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}{s}{artist}"
      label_alt: "{title}"
      separator: " - "
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      max_field_size:
        label: 20
        label_alt: 30
      show_thumbnail: true
      controls_only: false
      controls_left: true
      controls_hide: false
      thumbnail_alpha: 255
      thumbnail_padding: 8
      thumbnail_corner_radius: 16
      thumbnail_edge_fade: true
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 8
        thumbnail_size: 120
        thumbnail_fade_edges: true
        max_title_size: 60
        max_artist_size: 20
        show_source: true
        show_volume_slider: true
      media_menu_icons:
        play: "\ue768"
        pause: "\ue769"
        prev_track: "\ue892"
        next_track: "\ue893"
        mute: "\ue994"
        unmute: "\ue74f"
      scrolling_label:
        enabled: false
        update_interval_ms: 33
        style: "left" # can be "left", "right", "bounce", "bounce-ease"
        separator: " | "
        label_padding: 0
        always_scroll: false
        # Easing curve params: https://www.desmos.com/calculator/j7eamemxzi
        ease_slope: 20
        ease_pos: 0.8
        ease_min: 0.5
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
      media_menu:
        blur: true                           # Whether to apply a blur effect to the popup background.
        round_corners: true                  # Whether to round the corners of the popup.
        round_corners_type: "normal"         # The type of corner rounding. Can be "normal" or "symmetric".
        border_color: "system"               # The border color of the popup. Can be a HEX, None or "system".
        alignment: "right"                   # The alignment of the popup relative to the widget. Can be "left", "center", or "right".
        direction: "down"                    # The direction in which the popup opens. Can be "up" or "down".
        offset_top: 6                        # The vertical offset of the popup from the widget.
        offset_left: 0                       # The horizontal offset of the popup from the widget.
        thumbnail_corner_radius: 8           # The corner radius for the thumbnail in the popup.
        thumbnail_size: 120                  # The size of the thumbnail in the popup.
        max_title_size: 60                   # The maximum size for the title in the popup.
        max_artist_size: 20                  # The maximum size for the artist name in the popup.
        show_source: true                    # Whether to show the media source (e.g., Spotify, YouTube) in the popup.
        show_volume_slider: true             # Whether to show the volume slider in the popup. Volume control per application.
      media_menu_icons:
        play: "\ue768"       # Icon for the play button in the popup.
        pause: "\ue769"      # Icon for the pause button in the popup.
        prev_track: "\ue892" # Icon for the previous track button in the popup.
        next_track: "\ue893" # Icon for the next track button in the popup.
        mute: "\ue994"       # Icon for the mute button in the popup.
        unmute: "\ue74f"     # Icon for the unmute button in the popup.
      scrolling_label:
        enabled: false                # Whether to enable the scrolling label.
        update_interval_ms: 33       # The update interval for the scrolling label in milliseconds.
        style: "left"                 # The style of the scrolling label. Can be "left", "right", "bounce", or "bounce-ease".
        separator: " | "              # The separator between repeating text in "left" or "right" scrolling style.
        label_padding: 1              # The padding around the label in "bounce" and "bounce-ease" style. By default it's one character on each side.
        ease_slope: 20                # The easing slope for the bounce effect. Easing curve params: https://www.desmos.com/calculator/j7eamemxzi
        ease_pos: 0.8                 # The easing curve position for the bounce effect.
        ease_min: 0.5                 # The minimum value for the bounce effect easing curve.
      container_shadow:
        enabled: false          # Whether to enable the container shadow.
        color: "black"          # The color of the shadow. Can be a HEX value or color name.
        radius: 3               # The blur radius of the shadow.
        offset: [1, 1]          # The offset of the shadow in the format [x, y].
      label_shadow:
        enabled: false          # Whether to enable the label shadow.
        color: "black"          # The color of the shadow. Can be a HEX value or color name.
        radius: 3               # The blur radius of the shadow.
        offset: [1, 1]          # The offset of the shadow in the format [x, y].
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>{alarm}</span> {%a, %d %b %H:%M}"
      label_alt: "\uf017 {%d-%m-%y %H:%M:%S}"
      locale: ""
      update_interval: 1000
      timezones: []
      icons:
        clock_01 : "\udb85\udc3f"
        clock_02 : "\udb85\udc40"
        clock_03 : "\udb85\udc41"
        clock_04 : "\udb85\udc42"
        clock_05 : "\udb85\udc43"
        clock_06 : "\udb85\udc44"
        clock_07 : "\udb85\udc45"
        clock_08 : "\udb85\udc46"
        clock_09 : "\udb85\udc47"
        clock_10 : "\udb85\udc48"
        clock_11 : "\udb85\udc49"
        clock_12 : "\udb85\udc4a"
        clock_16 : "SNACK TIME !"
        clock_21 : "Zzz..."
        clock_22 : "Zzz..."
        clock_23 : "Zzz..."
      alarm_icons:
        enabled: "\uf0f3"
        disabled: "\uf0a2"
        snooze: "\uf1f6"
      calendar: 
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
        show_holidays: false
        show_week_numbers: true
        country_code: "AR"
        holiday_color: "#FF6464"
        extended: false
      callbacks:
        on_left: "toggle_calendar"
        on_middle: "next_timezone"
        on_right: "toggle_label"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: # Get your free API key from https://www.weatherapi.com/
      update_interval: 600
      hide_decimal: true
      location: # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
      callbacks:
        on_left: "toggle_card"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\ue312"
        cloudyNight: "\ue311"
        rainyDay: "\ue308"
        rainyNight: "\ue333"
        snowyIcyDay: "\ue30a"
        snowyIcyNight: "\ue335"
        blizzardDay: "\udb83\udf36"
        blizzardNight: "\udb83\udf36"
        foggyDay: "\ue303"
        foggyNight: "\ue346"
        thunderstormDay: "\ue30f"
        thunderstormNight: "\ue338"
        default: "\uebaa"
      weather_card:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        icon_size: 64
        show_hourly_forecast: True # Set to False to disable hourly forecast
        time_format: "12h" # can be 12h or 24h
        hourly_point_spacing: 76
        hourly_icon_size: 32 # better to set 16, 32 or 64 for better quality
        icon_smoothing: true # should be true for smoother icon or false for sharper icon if using 16, 32 or 64 for hourly_icon_size
        temp_line_width: 2 # can be 0 to hide the temperature line
        current_line_color: "#8EAEE8"
        current_line_width: 1 # can be 0 to hide the current hour line
        current_line_style: "dot"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      tooltip: false
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_left: "toggle_mute"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "<span>{icon}</span> {level}%"
      icons:
        normal: "\udb80\udf6c"
        muted: "\udb80\udf6d"
      callbacks:
        on_left: "toggle_mute"
        on_middle: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["\uf011", "Shutdown"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign Out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      label: "{data}"
      app_list:
        - { icon: "\ueb03", launch: "cmd /c Taskmgr" }
        - { icon: "\uf489", launch: "wt" }
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span> {count}"
      label_alt: "{count} notifications"
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: # Example path to folder with images
      change_automatically: false # Automatically change wallpaper
      update_interval: 60 # If change_automatically is true, update interval in seconds
      gallery:
        enabled: true
        blur: true
        image_width: 220
        image_per_page: 8
        show_buttons: true
        orientation: "portrait"
        image_spacing: 8
        lazy_load: true
        lazy_load_delay: 80
        lazy_load_fadein: 400
        image_corner_radius: 20
        enable_cache: true
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      cpu_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uf233</span> {virtual_mem_percent}"
      label_alt: "<span>\uf233</span> VIRT: {virtual_mem_percent}% SWAP: {swap_mem_percent}%"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      memory_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "{download_speed} | {upload_speed}"
      label_alt: "Download {download_speed} | Upload {upload_speed}"
      update_interval: 1000
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "left"
        direction: "down"
        offset_top: 6
        offset_left: 0
      callbacks:
        on_left: "toggle_menu"
        on_right: "toggle_label"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  windows_workspaces:
    type: "yasb.windows_desktops.WorkspaceWidget"
    options:
      label_workspace_btn: "\udb81\udc3d"
      label_workspace_active_btn: "\udb81\udc3e"
      btn_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  todo:
    type: "yasb.todo.TodoWidget"
    options:
      label: "<span>\uf0ae</span> {count}/{completed}"
      label_alt: "<span>\uf0ae</span> Tasks: {count}"
      # data_path: "~/Documents/my-todos.json"  # Optional: custom JSON file path
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
      icons:
        add: "\uf501 New Task"
        edit: "Edit"
        delete: "Delete"
        date: "\ue641"
        category: "\uf412"
        checked: "\udb80\udd34"
        unchecked: "\udb80\udd30"
        sort: "\ueab4"
        no_tasks: "\uf4a0"
      categories:
        default:
          label: "General"
        soon:
          label: "Complete soon"
        today:
          label: "End of day"
        urgent:
          label: "Urgent"
        important:
          label: "Important"
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb81\udf17</span>"
      menu_list:
      - { title: "User Home", path: "C:\\Users\\monst" }
      - { title: "Download", path: "C:\\Users\\monst\\Downloads" }
      - { title: "Documents", path: "C:\\Users\\monst\\Documents" }
      - { title: "Pictures", path: "C:\\Users\\monst\\OneDrive\\Pictures" }
      system_menu: true
      power_menu: true
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "System"
      offset_top: 6
      offset_left: 0
      alignment: "left"
      direction: "down"
      menu_labels:
        shutdown: "Shutdown"
        restart: "Restart"
        hibernate: "Hibernate"
        logout: "Logout"
        lock: "Lock"
        sleep: "Sleep"
        system: "System Settings"
        about: "About This PC"
        task_manager: "Task Manager"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 16
      min_bar_height: 2
      gradient: 1
      foreground: "#d4c5b0"
      gradient_color_1: '#8b6f47'
      gradient_color_2: '#b8956a'
      gradient_color_3: '#d4c5b0'
      bars_number: 20
      bar_spacing: 3
      bar_width: 3
      bar_type: "bars"
      framerate: 60
      noise_reduction: 5.85
      monstercat: 0
      waves: 1
      sensitivity: 70
      sleep_timer: 5
      hide_empty: true
      edge_fade: [8, 8]
      lower_cutoff_freq: 50
      higher_cutoff_freq: 10000
      callbacks:
        on_left: "do_nothing"
        on_middle: "do_nothing"
        on_right: "reload_cava"